const categories = [
  {
    id: 4,
    name: 'Phone & Tablets',
    image: 'https://images.pexels.com/photos/4300393/pexels-photo-4300393.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    keyword: 'phone, tablet, samsung, iphone, ios, android',
    images: () => (Array(18).fill(null).map((_, i) => `/img/categories/4/${ i + 1 }.png`)),
    banners: () => (Array(12).fill(null).map((_, i) => `/img/categories/4/banners/${ i + 1 }.jpg`)),
    filler: 'smartphones',
  },
  {
    id: 5,
    name: 'Computing',
    image: 'https://images.pexels.com/photos/3550484/pexels-photo-3550484.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    keyword: 'computer, laptop, desktop, windows, macbook',
    images: () => (Array(10).fill(null).map((_, i) => `/img/categories/5/${ i + 1 }.png`)),
    banners: () => (Array(5).fill(null).map((_, i) => `/img/categories/5/banners/${ i + 1 }.jpg`)),
    filler: 'computers',
  },
  {
    id: 6,
    name: 'Electronics',
    image: 'https://images.pexels.com/photos/3178938/pexels-photo-3178938.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    keyword: 'electric, standing fan, speaker',
    images: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/${ i + 1 }.png`)),
    banners: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/banners/${ i + 1 }.jpg`)),
    filler: 'electric appliances',
  },
  {
    id: 7,
    name: 'Fashion',
    image: 'https://images.pexels.com/photos/2703433/pexels-photo-2703433.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    keyword: 'fashion, cloth, shirt, shoes, bag',
    images: () => (Array(22).fill(null).map((_, i) => `/img/categories/7/${ i + 1 }.png`)),
    banners: () => (Array(22).fill(null).map((_, i) => `/img/categories/7/banners/${ i + 1 }.jpg`)),
    filler: 'fashion items',
  },
  {
    id: 3,
    name: 'Home & Office',
    image: 'https://images.pexels.com/photos/4050318/pexels-photo-4050318.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    keyword: 'home, office',
    images: () => (Array(6).fill(null).map((_, i) => `/img/categories/3/${ i + 1 }.png`)),
    banners: () => (Array(6).fill(null).map((_, i) => `/img/categories/3/banners/${ i + 1 }.jpg`)),
    filler: 'furnitures',
  },
  {
    id: 1,
    name: 'Supermarket',
    image: 'https://images.pexels.com/photos/6280415/pexels-photo-6280415.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    keyword: 'grocery',
    images: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/${ i + 1 }.png`)),
    banners: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/banners/${ i + 1 }.jpg`)),
    filler: 'groceries',
  },
  {
    id: 2,
    name: 'Health & Beauty',
    image: 'https://images.pexels.com/photos/775032/pexels-photo-775032.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    keyword: 'beauty',
    images: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/${ i + 1 }.png`)),
    banners: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/banners/${ i + 1 }.jpg`)),
    filler: 'make ups',
  },
  {
    id: 8,
    name: 'Baby Products',
    image: 'https://images.pexels.com/photos/459957/pexels-photo-459957.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    keyword: 'baby',
    images: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/${ i + 1 }.png`)),
    banners: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/banners/${ i + 1 }.jpg`)),
    filler: 'baby products',
  },
  {
    id: 9,
    name: 'Gaming',
    image: 'https://images.pexels.com/photos/159438/android-tv-game-controller-game-controller-video-game-controller-android-game-controller-159438.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    keyword: 'gaming, controller, pad',
    images: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/${ i + 1 }.png`)),
    banners: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/banners/${ i + 1 }.jpg`)),
    filler: 'games',
  },
  {
    id: 10,
    name: 'Sporting Goods',
    image: 'https://images.pexels.com/photos/159607/basketball-player-girls-basketball-girl-159607.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    keyword: 'sport, football, jersey',
    images: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/${ i + 1 }.png`)),
    banners: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/banners/${ i + 1 }.jpg`)),
    filler: 'sport items',
  },
  {
    id: 11,
    name: 'Automobile',
    image: 'https://images.pexels.com/photos/1231643/pexels-photo-1231643.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    keyword: 'automobile, car',
    images: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/${ i + 1 }.png`)),
    banners: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/banners/${ i + 1 }.jpg`)),
    filler: 'automobile items',
  },
  {
    id: 12,
    name: 'Others',
    image: 'https://images.pexels.com/photos/5310566/pexels-photo-5310566.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    keyword: 'all',
    images: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/${ i + 1 }.png`)),
    banners: () => (Array(6).fill(null).map((_, i) => `/img/categories/12/banners/${ i + 1 }.jpg`)),
    filler: 'products',
  }
];

export default categories;
