export default [
  { text: 'Abule Egba', value: 'Abule Egba' },
  { text: 'Agbara', value: 'Agbara' },
  { text: 'Agege', value: 'Agege' },
  { text: 'AJAO ESTATE', value: 'AJAO ESTATE' },
  { text: 'AMUWO', value: 'AMUWO' },
  { text: 'ANTHONY VILLAGE', value: 'ANTHONY VILLAGE' },
  { text: 'Apapa', value: 'Apapa' },
  { text: 'Badagry', value: 'Badagry' },
  { text: 'BERGER', value: 'BERGER' },
  { text: 'Coker', value: 'Coker' },
  { text: 'Doyin', value: 'Doyin' },
  { text: 'Ejigbo', value: 'Ejigbo' },
  { text: 'EPE', value: 'EPE' },
  { text: 'Fagba-Iju', value: 'Fagba-Iju' },
  { text: 'FESTAC', value: 'FESTAC' },
  { text: 'Gbagada', value: 'Gbagada' },
  { text: 'Ibeju Lekki', value: 'Ibeju Lekki' },
  { text: 'IGANDO', value: 'IGANDO' },
  { text: 'IJANIKIN', value: 'IJANIKIN' },
  { text: 'IJEGUN', value: 'IJEGUN' },
  { text: 'IJORA', value: 'IJORA' },
  { text: 'Ikeja', value: 'Ikeja' },
  { text: 'IKORODU', value: 'IKORODU' },
  { text: 'IKOTA', value: 'IKOTA' },
  { text: 'IKOTUN', value: 'IKOTUN' },
  { text: 'Ikoyi', value: 'Ikoyi' },
  { text: 'ILAJE-BARIGA', value: 'ILAJE-BARIGA' },
  { text: 'ILUPEJU', value: 'ILUPEJU' },
  { text: 'ISHERI', value: 'ISHERI' },
  { text: 'ISOLO', value: 'ISOLO' },
  { text: 'IYANA IBA', value: 'IYANA IBA' },
  { text: 'Iyana Ipaja', value: 'Iyana Ipaja' },
  { text: 'JAKANDE', value: 'JAKANDE' },
  { text: 'Ketu', value: 'Ketu' },
  { text: 'Lagos Island', value: 'Lagos Island' },
  { text: 'LAKOWE', value: 'LAKOWE' },
  { text: 'LEKKI', value: 'LEKKI' },
  { text: 'Magboro', value: 'Magboro' },
  { text: 'MARYLAND-ONIGBONGBO', value: 'MARYLAND-ONIGBONGBO' },
  { text: 'MEBANMU', value: 'MEBANMU' },
  { text: 'MILE 12', value: 'MILE 12' },
  { text: 'MILE 2', value: 'MILE 2' },
  { text: 'Mushin', value: 'Mushin' },
  { text: 'Ogba', value: 'Ogba' },
  { text: 'OGUDU', value: 'OGUDU' },
  { text: 'OJO', value: 'OJO' },
  { text: 'OJODU', value: 'OJODU' },
  { text: 'OJOTA', value: 'OJOTA' },
  { text: 'OKOKOMAIKO', value: 'OKOKOMAIKO' },
  { text: 'OKOTA', value: 'OKOTA' },
  { text: 'OREGUN', value: 'OREGUN' },
  { text: 'ORILE', value: 'ORILE' },
  { text: 'OSAPA-LEKKI', value: 'OSAPA-LEKKI' },
  { text: 'OSHODI', value: 'OSHODI' },
  { text: 'Palmgrove-Onipanu', value: 'Palmgrove-Onipanu' },
  { text: 'Satelite-Town', value: 'Satelite-Town' },
  { text: 'SOMOLU', value: 'SOMOLU' },
  { text: 'Surulere', value: 'Surulere' },
  { text: 'VI', value: 'VI' },
  { text: 'Yaba', value: 'Yaba' },
];
