export default [
  { "id": "aba", "name": "ABA" },
  { "id": "abeokuta", "name": "ABEOKUTA" },
  { "id": "abakaliki", "name": "ABAKALIKI" },
  { "id": "abuja", "name": "ABUJA" },
  { "id": "ado ekiti", "name": "ADO EKITI" },
  { "id": "akure", "name": "AKURE" },
  { "id": "asaba", "name": "ASABA" },
  { "id": "auchi", "name": "AUCHI" },
  { "id": "bauchi", "name": "BAUCHI" },
  { "id": "benin", "name": "BENIN" },
  { "id": "bonny", "name": "BONNY" },
  { "id": "calabar", "name": "CALABAR" },
  { "id": "eket", "name": "EKET" },
  { "id": "ekpoma", "name": "EKPOMA" },
  { "id": "enugu", "name": "ENUGU" },
  { "id": "gwagwalada", "name": "GWAGWALADA" },
  { "id": "ibadan", "name": "IBADAN" },
  { "id": "ife", "name": "IFE" },
  { "id": "ijebu-ode", "name": "IJEBU-ODE" },
  { "id": "ilorin", "name": "ILORIN" },
  { "id": "jos", "name": "JOS" },
  { "id": "kaduna", "name": "KADUNA" },
  { "id": "kano", "name": "KANO" },
  { "id": "katsina", "name": "KATSINA" },
  { "id": "lafia", "name": "LAFIA" },
  { "id": "lokoja", "name": "LOKOJA" },
  { "id": "lagos", "name": "LAGOS" },
  { "id": "makurdi", "name": "MAKURDI" },
  { "id": "maiduguri", "name": "MAIDUGURI" },
  { "id": "minna", "name": "MINNA" },
  { "id": "nnewi", "name": "NNEWI" },
  { "id": "nsukka", "name": "NSUKKA" },
  { "id": "onitsha", "name": "ONITSHA" },
  { "id": "owerri", "name": "OWERRI" },
  { "id": "oshogbo", "name": "OSHOGBO" },
  { "id": "port harcourt", "name": "PORT HARCOURT" },
  { "id": "warri", "name": "WARRI" },
  { "id": "sapele", "name": "SAPELE" },
  { "id": "sokoto/gusau", "name": "SOKOTO/GUSAU" },
  { "id": "umuahia", "name": "UMUAHIA" },
  { "id": "uyo", "name": "UYO" },
  { "id": "yenagoa", "name": "YENAGOA" },
  { "id": "yola/jalingo", "name": "YOLA/JALINGO" },
  { "id": "zaria", "name": "ZARIA" }
]
  .map(state => ({ text: state.name, value: state.id }))
  .sort((a, b) => a.text.match(/lagos/gi) ? -1 : b.text.match(/lagos/gi) ? 1 : 0);
